name: Person Service

on:
  push:
    branches: ['**']
    paths:
      - services/person-service/**
      - shared/**
      - package.json
      - package-lock.json
      - tsconfig.json
      - .nvmrc
      - .github/workflows/person-service.yml
      - .github/workflows/_deploy.yml

permissions:
  id-token: write
  contents: read

jobs:
  test:
    if: github.ref != 'refs/heads/master'
    uses: ./.github/workflows/_deploy.yml
    with:
      working-directory: services/person-service
      stack: PersonService-test
      stage: test
      environment: person-test

  prod:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/_deploy.yml
    with:
      working-directory: services/person-service
      stack: PersonService-prod
      stage: prod
      environment: person-prod
